name: CI NPM

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
    secrets:
      SENTRY_AUTH_TOKEN:
        required: true

jobs:
  continuous-integration:
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
    runs-on: ${{ inputs.runs-on }}
    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: npm
        cache-dependency-path: package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Health test
      run: npm run test

    - name: Build project
      run: npm run build