name: CI-APP

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
        default: ubuntu-latest


jobs:
  get-config:
    outputs:
      command: ${{ steps.format-config.outputs.command }}
    runs-on: ${{ inputs.runs-on }} 
    steps:      
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Format Arquive Config CI
        id: format-config
        uses: actions/github-script@v7
        with:
          script: |
            const configJson = require("./config-ci.json")
            let commands = {}
            for(command in configJson["run-command"]){
              commands[command] = configJson["run-command"][command]
            }
            core.setOutput("command", command)
  
  
  run-command:
    needs: get-config
    runs-on: ${{ inputs.runs-on }}
    strategy:
      matrix:
        command: ${{ needs.get-config.outputs.command }}
    steps:      
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/checkout@v3
        with:
          version: 18.x

      - name: Run Command CI
        run: |
         ${{ matrix.command }}

