name: Open PR

permissions:
  contents: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      branch-name:
        required: false
        type: string
        default: 'main'
    secrets:
      PAT_TOKEN:
        required: true

jobs:
  open-pr:
    outputs:
      pr-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Exibir valores de entrada
        run: |
          echo "Branch: ${{ inputs.branch-name }}"
          echo "Runs on: ${{ inputs.runs-on }}"
          echo "Repository: ${{ github.repository }}"

      - name: Criar Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          title: 'Pull Request Criado Automaticamente -> Develop'
          base: ${{ inputs.branch-name }}
          branch: ${{ github.ref }}
          labels: |
            automated pr
          assignees: pedrooliveiralopes
          reviewers: lucasgianine

  
