name: Open PR

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      base-branch-name:
        required: false
        type: string
        default: main
      head-branch-name:
        required: false
        type: string
        default: 'Não definida'
    secrets:
      PAT_TOKEN:
        required: true

jobs:
  open-pr:
    outputs:
      pr-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
      
      - name: Validando valores
        id: valida-valores
        uses: actions/github-script@v7
        with:
          script: |
            console.log(${{ inputs.head-branch-name }})
            console.log(${{ github.ref }})
            const headBranchName = ${{ inputs.head-branch-name }} == 'Não definida' ? ${{ github.ref }} : ${{ inputs.head-branch-name }}
            const baseBranch = ${{ inputs.base-branch-name }}.charAt(0).toUpperCase() + ${{ inputs.base-branch-name }}.slice(1)
            const title = `Pull Request Criado Automaticamente -> ${baseBranch}`
            core.setOutput('head-branch-name', headBranchName)
            core.setOutput('title', title)
            
      - name: Exibir valores de entrada
        run: |
          echo "Branch: ${{ inputs.base-branch-name }}"
          echo "Runs on: ${{ inputs.runs-on }}"
          echo "Repository: ${{ github.repository }}"

      - name: Criar Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          token: ${{ secrets.PAT_TOKEN }}
          title: 'Pull Request Criado Automaticamente -> '
          base: ${{ inputs.base-branch-name }}
          branch: ${{ steps.valida-branch.outputs.head-branch-name }}
          labels: |
            automated pr
          assignees: pedrooliveiralopes
          reviewers: lucasgianine

  
