name: Open PR

on:
  workflow_call:
    inputs:
      runs-on:
        required: false
        type: string
        default: ubuntu-latest
      branch-name:
        required: false
        type: string
        default: 'main'
    secrets:
      AUTH_TOKEN:
        required: true

jobs:
  open-pr:
    outputs:
      pr-number: ${{ steps.create-pull-request.outputs.pull-request-number }}
    runs-on: ${{ inputs.runs-on }}
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3 
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          
      
      - name: Criar Pull Request
        id: create-pull-request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          title: 'Pull Request Criado Automaticamente -> Develop'
          base: ${{ inputs.branch-name }}
          labels: |
            automated pr
          assignees: pedrooliveiralopes
          reviewers: pedrooliveiralopes
          delete-branch: true
          repository: ${{ github.repository }}

  