name: CI NPM Development

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - feat**
      - fix**
      - chore**

jobs:
  open-pr:
    uses: imerso-io/io-reusable-workflows/.github/workflows/open-pr.yml@feat/create-workflow-schedule
    with:
      base-branch-name: develop
      runs-on: ubuntu-latest
    secrets: inherit
  octopulls:
    needs: open-pr
    uses: imerso-io/io-reusable-workflows/.github/workflows/reviewer.yml@feat/create-workflow-schedule
    with:
      pull-request-number: ${{ needs.open-pr.outputs.pull-request-number }}
    secrets: inherit